services:
  - type: web
    name: wsn-laf-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsn_server.py
    envVars:
      - key: PORT
        value: 10000
